import Sidebar from "./_components/Sidebar";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col md:flex-row w-screen h-screen">
          <NextTopLoader />
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
