import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Urbanist } from "next/font/google";
import { Poppins } from "next/font/google";
import "./(root)/globals.css";
import StoreProvider from "./(root)/StoreProvider";
import NextTopLoader from "nextjs-toploader";
import StripeWrapper from "@/components/StripeWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Specify weights you want to use
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <StripeWrapper>
          <body className={poppins.className}>
            <NextTopLoader />
            {children}
          </body>
        </StripeWrapper>
      </StoreProvider>
    </html>
  );
}
